title: EndeavourOS Development
logo: https://raw.githubusercontent.com/endeavouros-team/artwork-images-logo/b53c4b90276e77d530785cb60d33c6bc3cc02f45/icons/endeavour-logo-sans-logotype.svg
description: information about EndeavourOS Development.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  repository_url: https://github.com/endeavouros-team
